theme: just-the-docs
title: "JHPC-Quantum Project Documentation"
search_enabled: true
color_scheme: "light"

logo: "/assets/images/jhpcq-logo.png"

aux_links:
  "JHPC-Quantum GitHub":
    - "https://github.com/jhpc-quantum"
  "RIKEN R-CCS":
    - "https://www.r-ccs.riken.jp"

# サイドバー階層の深さ
nav_sort: case_sensitive
